# Generated by Django 3.2.16 on 2023-12-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(help_text='Please input the full url which needs to be shortened.', max_length=2000)),
                ('short_url', models.SlugField(max_length=10, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('count_clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
